server:
  port: 19080  # ????? ???? ??? ?? ??

spring:
  main:
    web-application-type: reactive  # Spring ??????? ???? ? ???????? ???
  application:
    name: gateway-service  # ?????? ??? 'gateway-service'? ??
  cloud:
    gateway:
      routes:  # Spring Cloud Gateway? ??? ??
        - id: user-service  # ??? ???
          uri: lb://user-service  # 'order-service'?? ???? ?? ???? ???? ???
          predicates:
            - Path=/users/**  # /order/** ??? ???? ??? ? ???? ??
        - id: auth-service  # ??? ???
          uri: lb://auth-service  # 'auth-service'?? ???? ?? ???? ???? ???
          predicates:
            - Path=/auth/**  # /auth/signIn ??? ???? ??? ? ???? ??
      discovery:
        locator:
          enabled: true  # ??? ?????? ?? ???? ???? ????? ??


service:
  jwt:
    secret-key: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1"


eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/  # Eureka ??? URL? ??
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework.cloud.gateway: INFO
    com.sparta.cloud.movie_reservation_gateway: INFO